---
title: "CA and MCA of NYCABS dataset"
author: "Katerina Dimitrova, Jose Romero, Sergi Munoz"
date: "March 18, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r,include=FALSE}
#setwd("C://Users/Sergi/Desktop/Sergi/ADEI") #Change 
setwd("D:/ADEI/ADEI.git/trunk") #Change

```

# Load Required Packages: to be increased over the course
```{r}
rm(list=ls())
requiredPackages <- c("effects","FactoMineR","car", "factoextra","RColorBrewer","ggplot2","missMDA","mvoutlier","dplyr","ggmap","ggthemes","knitr","MVA")
missingPackages <- requiredPackages[!(requiredPackages %in% installed.packages()[,"Package"])]

if(length(missingPackages)) install.packages(missingPackages)
lapply(requiredPackages, require, character.only = TRUE)

# Useful function and Data
load("Taxi5000_raw_DataCleanv3.RData")
calcQ <- function(x) {
  s.x <- summary(x)
  iqr<-s.x[5]-s.x[2]
  list(souti=s.x[2]-3*iqr, mouti=s.x[2]-1.5*iqr, min=s.x[1], q1=s.x[2], q2=s.x[3],        q3=s.x[5], max=s.x[6], mouts=s.x[5]+1.5*iqr, souts=s.x[5]+3*iqr ) }
```

# CA: f.cost (discretization of Total_amount) vs f.hour and f.tt and period ...

```{r}
par(mfrow=c(1,1))
llvout<-which(df$mvout==TRUE);length(llvout)
#llout<-unique(c(llout,llvout))
tt<-table(df[,c("f.total","pick_up_period")])
tt
prop.table(tt,1)
prop.table(table(df$pick_up_period))
prop.table(tt,2)
prop.table(table(df$f.total))
# From the chi-square test we see that the p.value is less than 0.05 which meand that we can reject the Nul hypotesis thus the two factors are dependent. The df is 9 which means that the chi value of the threshold is 16,9 and we see that we have X-squared = 36,42 which is bigger than 16,9. => We can deffinetly reject the hypotesis. The Factors are dependent.
chisq.test(tt)

res.ca<-CA(tt)
lines(res.ca$row$coord[,1],res.ca$row$coord[,2],lwd=2,col="blue")

names(res.ca)
res.ca$row$contrib[,1:2]
res.ca$row$coord[,1:2]

fviz_eig(res.ca)
#From the variance and the eigenvalues we conclude that the first Dim explains a huge part of the data so we dont realy need the other dimentions. 
summary(res.ca,dig=2)
#We see that the the column points and the row points are far away from each other and thus not similar to each other. We can also interpret that at night the trips tend to be more expensive. In the afternoon is the middle price and about the cheap trips we cannot say anything definite since they are between valley and morning.
fviz_ca_biplot(res.ca,repel=TRUE)+theme_bw()

```

```{r}
tt<-table(df[,c("f.total","f.ttime")])
tt
prop.table(tt,1)
prop.table(table(df$f.ttime))
#Same as the Ca before this 2 facotrs are dependent because of the really small p.value and the big X-squared value. SO we can reject the null hypothesis.
chisq.test(tt)

#From the plot we see that the longer the trips is the more it costs which was also expected.
res.ca<-CA(tt)
lines(res.ca$row$coord[,1],res.ca$row$coord[,2],lwd=2,col="blue")
#We need to consider the first 2 dimentions which together explain 90% of the data.
summary(res.ca)
res.ca$row$contrib[,1:2]
res.ca$row$coord[,1:2]
res.ca$row$cos2[,1:2]
#The 2st two eigenectors give us 90% of the variance so they are sufficient. 
res.ca$eig
sum(res.ca$eig[1:2,1])/sum(res.ca$eig[1:3,1])
sum(res.ca$eig[1:3,1])
res.ca$call$marge.col

fviz_eig(res.ca)
summary(res.ca,dig=2)
fviz_ca_biplot(res.ca,repel=TRUE)+theme_bw()


#tt<-table(df[,c("AnyTip","f.ttime")])  # No tinc sentit fer-ho
#tt
#res.ca<-CA(tt)
#fviz_ca_biplot(res.ca,repel=TRUE)+theme_bw()

```

# MCA using multivariant

```{r}
par(mfrow=c(1,1))
names(df)
#explain we don't use this variable cause it is too bad balanced
summary(df$Store_and_fwd_flag)
#add espeed factor as active (we need to generate it)
vars_dis <- names(df)[c(1,19,20,22,29:40,42)]
vars_cat<-names(df)[c(1, 5,19:20,22,27, 29:42)]#10, 21 not working
#add f.totalamount as quali.sup
res.mca<-MCA(df[,c(vars_cat,"Total_amount")],quali.sup=c(5,13),quanti.sup=21)

# We see that all of the eigenvectors are really small, so we will use a similiar rule like in the PCA and take all EW with value >1 => the first 26 dimentions.
fviz_eig(res.mca)
fviz_screeplot(res.mca, addlabels = TRUE, ylim = c(0, 45))
get_eigenvalue(res.mca)
names(res.mca)
summary(res.mca,nbelements=50)
mean(res.mca$eig) 

# Individual Representation
plot.MCA(res.mca,choix=c("ind"),cex=0.8)
plot.MCA(res.mca,choix=c("ind"),invisible=c("ind"),cex=0.8)

# Representation of categories
plot.MCA(res.mca,choix=c("ind"),invisible=c("ind"),axes=c(1,2))
lines(res.mca$quali.sup$coord[3:4, 1],res.mca$quali.sup$coord[3:4,2],lwd=2,col="darkgreen") # Trencada dels nivells de f.fare_amount #??
lines(res.mca$quali.sup$coord[1:2,1],res.mca$quali.sup$coord[1:2,2],lwd=2,col="darkblue") # Trencada AnyTip
names(res.mca)

# Contributions of rows to dimension 1
fviz_contrib(res.mca, choice = "var", axes = 1, top = 15)
# Contributions of rows to dimension 2
fviz_contrib(res.mca, choice = "var", axes = 2, top = 15)
# Total contribution to dimension 1 and 2
fviz_contrib(res.mca, choice = "var", axes = 1:2, top = 15)
#we see that the the provider of the record,categories of the rate code are most contributive and the the type of the payment. Also it makes difference when it is night.
head(round(res.mca$var$contrib,2), 10)

plot.MCA(res.mca,choix=c("ind"),invisible=c("ind"),axes=c(3,4))
plot.MCA(res.mca,choix=c("var"),axes=c(3,4))

# Use modern ggplot facilities
names(res.mca)
fviz_eig(res.mca)
fviz_cos2(res.mca, choice = "var", axes = 1:2)+theme_bw()
fviz_contrib(res.mca, choice = "var", axes = 3:4)+theme_bw()
fviz_mca_var(res.mca, col.var="contrib",repel=TRUE)+
    scale_color_gradient2(low="green", mid="blue", 
    high="red", midpoint=0.75)+theme_bw()
fviz_mca_var(res.mca, col.var="contrib",repel=F)+
    scale_color_gradient2(low="green", mid="blue", 
    high="red", midpoint=0.75)+theme_bw()

fviz_mca_biplot(res.mca, invisible="ind",axes=1:2,repel=FALSE)+theme_bw()
#fviz_mca_biplot(res.mca, axes=1:2,repel=TRUE,arrows=c(TRUE,FALSE))+theme_bw()
```

# Synthesis through HCPC: Hierarchical Clustering

```{r}
###
### Clustering the individuals
### Before, hou have to perform a MCA with the number of axes 
### that you have decided to take into account (indicated through ncp=)
?HCPC
res.mca<-MCA(df[,c(vars_cat,"Total_amount")],quali.sup=c(5,13),quanti.sup=21,ncp=26)
res.hcpc<-HCPC(res.mca,nb.clust=8,order=TRUE)
names(res.hcpc)

fviz_cluster(res.hcpc, geom = "point", main = "Factor map")

#Anytip
vars_con_pca<-c(6,7,8,9,10,11,12,13,14,15,16,17,18,22,23,24,25,26) 
res.pca<-PCA(df[,vars_con_pca], quanti.sup = 13, quali.sup = 14, ncp = 6 ) # TotalAmount and AnyTip
res.hcpcPCA <-HCPC(res.pca, nb.clust = 8, order=TRUE)
table (res.hcpc$data.clust$clust, res.hcpcPCA$data.clust$clust)
claHPPCA<-factor(res.hcpcPCA$data.clust$clust,labels=paste("kHP-",1:8))
claHP<-factor(res.hcpc$data.clust$clust,levels=c(5,7,1,4,2,8,3,6),labels=c("kKM-5","kKM-7","kKM-1","kKM-4","kKM-2","kKM-8","kKM-3","kKM-6"))
tt<-table(claHPPCA,claHP)
tt
sum(diag(tt)/sum(tt))
#F.total
vars_con_pca<-c(6,7,8,9,10,11,12,13,14,15,16,17,18,23,24,25,26,41) 
names(df[,vars_con_pca])
names(df)
res.pca<-PCA(df[,vars_con_pca], quanti.sup = 13, quali.sup = 18, ncp = 6 ) # TotalAmount and f.total
res.hcpcPCA <-HCPC(res.pca, nb.clust = 8, order=TRUE)
claHPPCA<-factor(res.hcpcPCA$data.clust$clust,labels=paste("kHP-",1:8))
claHP<-factor(res.hcpc$data.clust$clust,levels=c(4,7,1,5,2,8,3,6),labels=c("kKM-5","kKM-7","kKM-1","kKM-4","kKM-2","kKM-8","kKM-3","kKM-6"))
tt<-table(claHPPCA,claHP)
tt
sum(diag(tt)/sum(tt))
```
